# Generated by Django 5.0.3 on 2024-03-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="image",
            field=models.ImageField(null=True, upload_to="blog"),
        ),
    ]
